FROM rocker/verse
RUN R -e "install.packages(\"shiny\")"
RUN R -e "install.packages(\"plotly\")"
RUN R -e "install.packages(\"gridExtra\")"
RUN R -e "install.packages(\"caret\")"
RUN R -e "install.packages(\"MASS\")"
RUN R -e "install.packages(\"class\")"
RUN R -e "install.packages(\"e1071\")"
RUN R -e "install.packages(\"randomForest\")"
RUN R -e "install.packages(\"rfm\")"
RUN R -r "install.packages(\"tinytex\"); tinytex::install_tinytex();"
